import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App Name
    "app.name": "Daily Spiral",
    "app.subtitle": "Life Management",
    
    // Navigation
    "nav.home": "Home",
    "nav.expenses": "Expenses",
    "nav.mood": "Mood",
    "nav.habits": "Habits",
    "nav.plan": "Plan",
    "nav.insights": "Insights",
    "nav.settings": "Settings",
    
    // Daily Plan
    "plan.title": "Plan",
    "plan.newEvent": "New Event",
    "plan.editEvent": "Edit Event",
    "plan.eventTitle": "Event Title",
    "plan.placeholder": "What's the plan?",
    "plan.starts": "Starts",
    "plan.ends": "Ends",
    "plan.color": "Color",
    "plan.delete": "Delete",
    "plan.update": "Update",
    "plan.create": "Create Event",
    "plan.eventCreated": "Event created",
    "plan.eventUpdated": "Event updated",
    "plan.eventDeleted": "Event deleted",
    "plan.day": "Day",
    "plan.week": "Week",
    "plan.month": "Month",
    "plan.year": "Year",
    "plan.comingSoon": "Coming Soon",
    "plan.today": "Today",
    "plan.add": "Add",
    "plan.more": "more",
    
    // Home Page
    "home.welcome": "Welcome Back",
    "home.quickActions": "Quick Actions",
    "home.addExpense": "Add Expense",
    "home.recordMood": "Daily Mood",
    "home.checkHabit": "Habit Check",
    "home.todaysSummary": "Today's Summary",
    "home.expenses": "Expenses",
    "home.mood": "Mood",
    "home.habits": "Habits Completed",
    "home.recentActivity": "Recent Activity",
    "home.noActivity": "No activity yet",
    "home.dailyQuote": "Daily Quote",
    
    // Expenses
    "expenses.title": "Expense Tracking",
    "expenses.subtitle": "Track your income and spending",
    "expenses.addRecord": "Add Record",
    "expenses.addExpenseRecord": "Add Expense Record",
    "expenses.type": "Type",
    "expenses.expense": "Expense",
    "expenses.income": "Income",
    "expenses.amount": "Amount",
    "expenses.category": "Category",
    "expenses.date": "Date",
    "expenses.note": "Note",
    "expenses.save": "Save",
    "expenses.totalExpense": "Total Expense",
    "expenses.totalIncome": "Total Income",
    "expenses.balance": "Balance",
    "expenses.transactions": "Transactions",
    "expenses.monthlyTrend": "Monthly Trend",
    "expenses.categoryBreakdown": "Category Breakdown",
    "expenses.recentTransactions": "Recent Transactions",
    "expenses.noTransactions": "No transactions yet",
    "expenses.addFirst": "Add your first transaction",
    "expenses.delete": "Delete",
    "expenses.deleted": "Record deleted",
    "expenses.saved": "Record saved",
    "expenses.enterAmount": "Please enter amount",
    "expenses.selectCategory": "Please select category",
    
    // Categories
    "category.food": "Food",
    "category.transport": "Transport",
    "category.shopping": "Shopping",
    "category.entertainment": "Entertainment",
    "category.utilities": "Utilities",
    "category.health": "Health",
    "category.salary": "Salary",
    "category.bonus": "Bonus",
    "category.investment": "Investment",
    "category.other": "Other",
    "category.custom": "Custom",
    
    // Mood
    "mood.title": "Mood Diary",
    "mood.subtitle": "Track your emotional journey",
    "mood.selectDate": "Select Date",
    "mood.howAreYou": "How are you feeling?",
    "mood.veryBad": "Very Bad",
    "mood.excellent": "Excellent",
    "mood.addNote": "Add a note (optional)",
    "mood.placeholder": "What happened today? How do you feel?",
    "mood.saveRecord": "Save Record",
    "mood.dailyRecommendations": "Daily Recommendations",
    "mood.basedOnMood": "Based on your mood",
    "mood.monthlyTrend": "Monthly Mood Trend",
    "mood.weeklyTrend": "Weekly Mood Trend",
    "mood.avgMood": "Average Mood",
    "mood.bestDay": "Best Day",
    "mood.saved": "Mood record saved",
    "mood.moodHistory": "Mood History",
    "mood.terrible": "Terrible",
    "mood.bad": "Bad",
    "mood.okay": "Okay",
    "mood.good": "Good",
    "mood.amazing": "Amazing",
    "mood.rec.comfortPlaylist": "Comforting Playlist",
    "mood.rec.music20min": "Music • 20 min",
    "mood.rec.deepBreathing": "Deep Breathing",
    "mood.rec.wellness5min": "Wellness • 5 min",
    "mood.rec.ventJournal": "Vent Journaling",
    "mood.rec.writing10min": "Writing • 10 min",
    "mood.rec.lofiBeats": "Lo-Fi Beats",
    "mood.rec.musicFocus": "Music • Focus",
    "mood.rec.shortWalk": "Short Walk",
    "mood.rec.health15min": "Health • 15 min",
    "mood.rec.readChapter": "Read a Chapter",
    "mood.rec.relax15min": "Relax • 15 min",
    "mood.rec.upbeatHits": "Upbeat Hits",
    "mood.rec.musicEnergy": "Music • Energy",
    "mood.rec.quickWorkout": "Quick Workout",
    "mood.rec.fitness20min": "Fitness • 20 min",
    "mood.rec.callFriend": "Call a Friend",
    "mood.rec.social10min": "Social • 10 min",
    
    // Habits
    "habits.title": "Habit Tracking",
    "habits.subtitle": "Build better habits, become a better you",
    "habits.addHabit": "Add Habit",
    "habits.addNewHabit": "Add New Habit",
    "habits.habitName": "Habit Name",
    "habits.placeholder": "e.g., Exercise 30 minutes daily",
    "habits.selectColor": "Select Color",
    "habits.save": "Save",
    "habits.weeklyCompletion": "Weekly Completion",
    "habits.habitCount": "Habit Count",
    "habits.longestStreak": "Longest Streak",
    "habits.days": "days",
    "habits.tracker": "Habit Tracker",
    "habits.habit": "Habit",
    "habits.streak": "Streak",
    "habits.noHabits": "No habits added yet",
    "habits.addFirst": "Add your first habit",
    "habits.added": "Habit added",
    "habits.deleted": "Habit deleted",
    "habits.enterName": "Please enter habit name",
    "habits.enterColorDesc": "Enter habit name, color and frequency",
    "habits.everyDay": "Every Day",
    "habits.specDays": "Spec Days",
    "habits.weeklyGoal": "Weekly Goal",
    
    // Insights
    "insights.title": "AI Insights",
    "insights.subtitle": "Discover patterns in your life data",
    "insights.weeklyReport": "Weekly Report",
    "insights.generateReport": "Generate Report",
    "insights.generating": "Generating...",
    "insights.analyzing": "Analyzing your data...",
    "insights.noData": "No data yet",
    "insights.noDataDesc": "Start recording your expenses, moods, and habits to generate insights.",
    "insights.dataRange": "Data Range",
    "insights.to": "to",
    "insights.overview": "Overview",
    "insights.moodAnalysis": "Mood Analysis",
    "insights.expenseInsights": "Expense Insights",
    "insights.habitProgress": "Habit Progress",
    "insights.lifeSpiral": "Life Spiral",
    "insights.recommendations": "Recommendations",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your data and preferences",
    "settings.dataManagement": "Data Management",
    "settings.exportData": "Export Data",
    "settings.exportDesc": "Download all your data as a JSON file",
    "settings.export": "Export",
    "settings.exporting": "Exporting...",
    "settings.clearData": "Clear All Data",
    "settings.clearDesc": "Permanently delete all your records",
    "settings.clear": "Clear",
    "settings.about": "About",
    "settings.version": "Version",
    "settings.description": "A comprehensive life management tool integrating expense tracking, mood diary, habit tracking, and AI insights.",
    "settings.privacy": "Privacy",
    "settings.privacyDesc": "All data is stored locally in your browser and never uploaded to any server.",
    "settings.confirmClear": "Confirm clearing all data?",
    "settings.confirmClearDesc": "This will permanently delete all expense, mood, and habit records. This action cannot be undone. We recommend exporting your data before clearing.",
    "settings.cancel": "Cancel",
    "settings.confirmClearButton": "Confirm Clear",
    "settings.dataCleared": "All data cleared",
    "settings.dataExported": "Data exported successfully",
    "settings.account": "Personal Account",
    "settings.loginViaEmail": "Logged in via Email",
    "settings.signOut": "Sign Out",
    
    // Welcome
    "welcome.title": "Welcome to Daily Spiral",
    "welcome.description": "Step into your daily spiral of growth. Track your journey, discover patterns, and become a better you.",
    "welcome.features": "Powerful Features",
    "welcome.expenseSystem": "Expense Tracking",
    "welcome.expenseSystemDesc": "Manage your finances with a simple yet powerful income and expense tracker.",
    "welcome.moodDiary": "Mood Journal",
    "welcome.moodDiaryDesc": "Record your daily emotions and see how your mood fluctuates over time.",
    "welcome.habitTracking": "Habit Building",
    "welcome.habitTrackingDesc": "Create positive habits and track your consistency with our intuitive tracker.",
    "welcome.aiInsights": "AI Deep Insights",
    "welcome.aiInsightsDesc": "Get personalized feedback and patterns based on your life data.",
    "welcome.highlights": "Unique Highlights",
    "welcome.spiralViz": "Spiral Visualization",
    "welcome.spiralVizDesc": "A unique way to view your life's progress and cycles.",
    "welcome.dailyQuote": "Daily Inspiration",
    "welcome.dailyQuoteDesc": "Get motivated with quotes tailored to your current mood.",
    "welcome.quickRecord": "Quick Actions",
    "welcome.quickRecordDesc": "One-tap recording for your busiest days.",
    "welcome.privacyTitle": "Your Privacy Matters",
    "welcome.privacyText": "All your personal data is stored locally in your browser and synced securely with Supabase if you are logged in. We never sell your data.",
    "welcome.getStarted": "Get Started",
    
    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.thisWeek": "This Week",
    "common.thisMonth": "This Month",
    "common.total": "Total",
    "common.custom": "Custom",
    "mood.low": "Low",
    "mood.stable": "Stable",
    "mood.joyful": "Joyful",
  },
  zh: {
    // App Name
    "app.name": "每日生活记",
    "app.subtitle": "生活管理",
    
    // Navigation
    "nav.home": "主页",
    "nav.expenses": "记账",
    "nav.mood": "心情",
    "nav.habits": "习惯",
    "nav.plan": "日程",
    "nav.insights": "洞察",
    "nav.settings": "设置",
    
    // Daily Plan
    "plan.title": "日程规划",
    "plan.newEvent": "新增日程",
    "plan.editEvent": "编辑日程",
    "plan.eventTitle": "日程标题",
    "plan.placeholder": "有什么计划？",
    "plan.starts": "开始时间",
    "plan.ends": "结束时间",
    "plan.color": "标记颜色",
    "plan.delete": "删除",
    "plan.update": "更新",
    "plan.create": "创建日程",
    "plan.eventCreated": "日程已创建",
    "plan.eventUpdated": "日程已更新",
    "plan.eventDeleted": "日程已删除",
    "plan.day": "日",
    "plan.week": "周",
    "plan.month": "月",
    "plan.year": "年",
    "plan.comingSoon": "即将推出",
    "plan.today": "今天",
    "plan.add": "添加",
    "plan.more": "更多",
    
    // Home Page
    "home.welcome": "欢迎回来",
    "home.quickActions": "快速操作",
    "home.addExpense": "添加支出",
    "home.recordMood": "记录心情",
    "home.checkHabit": "习惯打卡",
    "home.todaysSummary": "今日摘要",
    "home.expenses": "支出",
    "home.mood": "心情",
    "home.habits": "习惯完成",
    "home.recentActivity": "最近活动",
    "home.noActivity": "暂无活动",
    "home.dailyQuote": "每日一句",
    
    // Expenses
    "expenses.title": "支出追踪",
    "expenses.subtitle": "记录您的收入和支出",
    "expenses.addRecord": "添加记录",
    "expenses.addExpenseRecord": "添加收支记录",
    "expenses.type": "类型",
    "expenses.expense": "支出",
    "expenses.income": "收入",
    "expenses.amount": "金额",
    "expenses.category": "分类",
    "expenses.date": "日期",
    "expenses.note": "备注",
    "expenses.save": "保存",
    "expenses.totalExpense": "总支出",
    "expenses.totalIncome": "总收入",
    "expenses.balance": "结余",
    "expenses.transactions": "每周交易",
    "expenses.monthlyTrend": "月度趋势",
    "expenses.categoryBreakdown": "分类占比",
    "expenses.recentTransactions": "最近交易",
    "expenses.noTransactions": "还没有交易记录",
    "expenses.addFirst": "添加第一笔交易",
    "expenses.delete": "删除",
    "expenses.deleted": "记录已删除",
    "expenses.saved": "记录已保存",
    "expenses.enterAmount": "请输入金额",
    "expenses.selectCategory": "请选择分类",
    
    // Categories
    "category.food": "餐饮",
    "category.transport": "交通",
    "category.shopping": "购物",
    "category.entertainment": "娱乐",
    "category.utilities": "生活缴费",
    "category.health": "医疗",
    "category.salary": "工资",
    "category.bonus": "奖金",
    "category.investment": "投资收益",
    "category.other": "其他",
    "category.custom": "自定义",
    
    // Mood
    "mood.title": "心情日记",
    "mood.subtitle": "追踪您的情绪旅程",
    "mood.selectDate": "选择日期",
    "mood.howAreYou": "今天感觉如何？",
    "mood.veryBad": "很糟",
    "mood.excellent": "超棒",
    "mood.addNote": "添加笔记（可选）",
    "mood.placeholder": "今天发生了什么？你的感受如何？",
    "mood.saveRecord": "保存记录",
    "mood.dailyRecommendations": "今日建议",
    "mood.basedOnMood": "根据你的心情",
    "mood.monthlyTrend": "月度趋势",
    "mood.weeklyTrend": "每周趋势",
    "mood.avgMood": "平均心情",
    "mood.bestDay": "最佳表现",
    "mood.saved": "心情记录已保存",
    "mood.moodHistory": "历史记录",
    "mood.terrible": "很糟",
    "mood.bad": "较差",
    "mood.okay": "一般",
    "mood.good": "不错",
    "mood.amazing": "超棒",
    "mood.rec.comfortPlaylist": "舒缓歌单",
    "mood.rec.music20min": "音乐 • 20分钟",
    "mood.rec.deepBreathing": "深呼吸",
    "mood.rec.wellness5min": "身心健康 • 5分钟",
    "mood.rec.ventJournal": "情绪宣泄日记",
    "mood.rec.writing10min": "写作 • 10分钟",
    "mood.rec.lofiBeats": "低保真节奏",
    "mood.rec.musicFocus": "音乐 • 专注",
    "mood.rec.shortWalk": "散步",
    "mood.rec.health15min": "健康 • 15分钟",
    "mood.rec.readChapter": "读一章节书",
    "mood.rec.relax15min": "放松 • 15分钟",
    "mood.rec.upbeatHits": "欢快热门歌曲",
    "mood.rec.musicEnergy": "音乐 • 能量",
    "mood.rec.quickWorkout": "快速锻炼",
    "mood.rec.fitness20min": "健身 • 20分钟",
    "mood.rec.callFriend": "给朋友打个电话",
    "mood.rec.social10min": "社交 • 10分钟",
    
    // Habits
    "habits.title": "习惯打卡",
    "habits.subtitle": "培养良好习惯，成就更好的自己",
    "habits.addHabit": "添加习惯",
    "habits.addNewHabit": "添加新习惯",
    "habits.habitName": "习惯名称",
    "habits.placeholder": "例如：每天运动30分钟",
    "habits.selectColor": "选择颜色",
    "habits.save": "保存",
    "habits.weeklyCompletion": "本周完成率",
    "habits.habitCount": "习惯数量",
    "habits.longestStreak": "最长连续",
    "habits.days": "天",
    "habits.tracker": "习惯打卡表",
    "habits.habit": "习惯",
    "habits.streak": "连续",
    "habits.noHabits": "还没有添加习惯",
    "habits.addFirst": "添加第一个习惯",
    "habits.added": "习惯已添加",
    "habits.deleted": "习惯已删除",
    "habits.enterName": "请输入习惯名称",
    "habits.enterColorDesc": "设置习惯名称、颜色和频率",
    "habits.everyDay": "每天",
    "habits.specDays": "特定日期",
    "habits.weeklyGoal": "每周目标",
    
    // Insights
    "insights.title": "AI 洞察",
    "insights.subtitle": "发现您的生活数据中的模式",
    "insights.weeklyReport": "周度报告",
    "insights.generateReport": "生成报告",
    "insights.generating": "生成中...",
    "insights.analyzing": "分析数据中...",
    "insights.noData": "暂无数据",
    "insights.noDataDesc": "开始记录您的支出、心情和习惯以生成洞察报告。",
    "insights.dataRange": "数据范围",
    "insights.to": "至",
    "insights.overview": "总览",
    "insights.moodAnalysis": "心情分析",
    "insights.expenseInsights": "支出洞察",
    "insights.habitProgress": "习惯进度",
    "insights.lifeSpiral": "生命螺旋",
    "insights.recommendations": "建议",
    
    // Settings
    "settings.title": "设置",
    "settings.subtitle": "管理您的数据和偏好",
    "settings.dataManagement": "数据管理",
    "settings.exportData": "导出数据",
    "settings.exportDesc": "将所有数据下载为 JSON 文件",
    "settings.export": "导出",
    "settings.exporting": "导出中...",
    "settings.clearData": "清除所有数据",
    "settings.clearDesc": "永久删除所有记录",
    "settings.clear": "清除",
    "settings.about": "关于",
    "settings.version": "版本",
    "settings.description": "一款融合记账、情绪记录、习惯打卡与 AI 深度反馈的全维度个人生活管理工具。",
    "settings.privacy": "隐私",
    "settings.privacyDesc": "所有数据仅存储在您的浏览器本地，不会上传到任何服务器。",
    "settings.confirmClear": "确认清除所有数据？",
    "settings.confirmClearDesc": "此操作将永久删除所有记账、心情、习惯记录。此操作不可恢复。建议在清除前先导出数据作为备份。",
    "settings.cancel": "取消",
    "settings.confirmClearButton": "确认清除",
    "settings.dataCleared": "所有数据已清除",
    "settings.dataExported": "数据导出成功",
    "settings.account": "个人账户",
    "settings.loginViaEmail": "邮箱登录",
    "settings.signOut": "退出登录",
    
    // Welcome
    "welcome.title": "欢迎使用每日生活记",
    "welcome.description": "步入您的每日成长螺旋。追踪旅程，发现规律，成就更好的自己。",
    "welcome.features": "强大功能",
    "welcome.expenseSystem": "收支追踪",
    "welcome.expenseSystemDesc": "通过简单而强大的收入和支出追踪功能管理您的财务。",
    "moodDiary": "心情日记",
    "welcome.moodDiary": "心情日记",
    "welcome.moodDiaryDesc": "记录每日情绪，观察心情随时间的波动规律。",
    "welcome.habitTracking": "习惯养成",
    "welcome.habitTrackingDesc": "创建积极习惯，通过直观的追踪器保持一致性。",
    "welcome.aiInsights": "AI 深度洞察",
    "welcome.aiInsightsDesc": "基于您的生活数据获得个性化反馈和模式分析。",
    "welcome.highlights": "独特亮点",
    "welcome.spiralViz": "螺旋可视化",
    "welcome.spiralVizDesc": "一种独特的视角，查看生活进度与周期。",
    "welcome.dailyQuote": "每日灵感",
    "welcome.dailyQuoteDesc": "根据您当前的心情，获得定制的励志语录。",
    "welcome.quickRecord": "快速操作",
    "welcome.quickRecordDesc": "为忙碌的日子提供一键式记录功能。",
    "welcome.privacyTitle": "您的隐私至关重要",
    "welcome.privacyText": "您的所有个人数据都存储在浏览器本地，并在登录后安全同步至 Supabase。我们绝不出售您的数据。",
    "welcome.getStarted": "开始体验",
    
    // Common
    "common.loading": "加载中...",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.back": "返回",
    "common.next": "下一步",
    "common.previous": "上一步",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.today": "今天",
    "common.yesterday": "昨天",
    "common.thisWeek": "本周",
    "common.thisMonth": "本月",
    "common.total": "总计",
    "common.custom": "自定义",
    "mood.low": "低迷",
    "mood.stable": "平稳",
    "mood.joyful": "愉悦",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("dailyspiral_language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("dailyspiral_language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
